name: action-validator
description: Runs action-validator with verbose output on files tracked by Git.
inputs:
  version:
    description: action-validator version to install
    required: false
    default: "0.8.0"
  destination:
    description: Installation destination directory
    required: false
    default: /usr/local/bin

runs:
  using: "composite"
  steps:
    - name: Convert architecture
      id: arch
      shell: sh
      env:
        runner_arch: ${{ runner.arch }} # Possible values are X86, X64, ARM, or ARM64.
      run: |
        case "$runner_arch" in
          X64) echo "arch=amd64" >> "$GITHUB_OUTPUT" ;;
          ARM64) echo "arch=arm64" >> "$GITHUB_OUTPUT" ;;
          *) echo "Unsupported architecture: $runner_arch" >&2; exit 1 ;;
        esac
    - name: Convert OS
      id: os
      shell: sh
      env:
        runner_os: ${{ runner.os }} # Possible values are Linux, Windows, or macOS.
      run: |
        case "$runner_os" in
          Linux) echo "os=linux" >> "$GITHUB_OUTPUT" ;;
          macOS) echo "os=darwin" >> "$GITHUB_OUTPUT" ;;
          *) echo "Unsupported OS: $runner_os" >&2; exit 1 ;;
        esac
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.destination }}/action-validator
        key: action-validator-${{ inputs.version }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      shell: sh
      env:
        bin: https://github.com/mpalmer/action-validator/releases/download/v${{ inputs.version }}/action-validator_linux_amd64
        dest: ${{ inputs.destination }}/action-validator
      run: |
        curl -sSL "$bin" -o "$dest"
        chmod +x "$dest"
    - name: Run
      shell: sh
      run: |
        git ls-files -z ".github/*/*.yml" "*/action.yml" | xargs -0 action-validator --verbose
