name: action-validator
description: Downloads, caches, and runs action-validator with verbose output on files tracked by Git.
inputs:
  version:
    description: action-validator version in semver format without the 'v' prefix
    required: false
    default: "0.8.0"
  install-path:
    description: Installation path without trailing slash for the binary
    required: false
    default: /usr/local/bin
branding:
  icon: check
  color: green
runs:
  using: "composite"
  steps:
    - name: Convert architecture
      id: arch
      shell: sh
      env:
        runner_arch: ${{ runner.arch }} # Possible values are X86, X64, ARM, or ARM64.
      run: |
        case "$runner_arch" in
          X64) echo "arch=amd64" >> "$GITHUB_OUTPUT" ;;
          ARM64) echo "arch=arm64" >> "$GITHUB_OUTPUT" ;;
          *) echo "Unsupported architecture: $runner_arch" >&2; exit 1 ;;
        esac
    - name: Convert OS
      id: os
      shell: sh
      env:
        runner_os: ${{ runner.os }} # Possible values are Linux, Windows, or macOS.
      run: |
        case "$runner_os" in
          Linux) echo "os=linux" >> "$GITHUB_OUTPUT" ;;
          macOS) echo "os=darwin" >> "$GITHUB_OUTPUT" ;;
          *) echo "Unsupported OS: $runner_os" >&2; exit 1 ;;
        esac
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.install-path }}/action-validator
        key: action-validator_v${{ inputs.version }}_${{ steps.os.outputs.os }}_${{ steps.arch.outputs.arch }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        version: ${{ inputs.version }}
        os: ${{ steps.os.outputs.os }}
        arch: ${{ steps.arch.outputs.arch }}
        output: ${{ inputs.install-path }}/action-validator
      run: |
        echo "gh release download \"v$version\" --repo mpalmer/action-validator --pattern \"action-validator_${os}_$arch\" --output \"$output\""
        gh release download "v$version" --repo mpalmer/action-validator --pattern "action-validator_${os}_$arch" --output "$output"
        chmod +x "$output"
    - name: Run
      shell: sh
      run: |
        git ls-files -z ".github/workflows/*.yml" "*/action.yml" ".github/workflows/*.yaml" "*/action.yaml" | xargs -0 action-validator --verbose
